# Site settings
baseurl = "https://mingrammer.com/"
title = "mingrammer's note"
theme = "hugo-theme-cactus-plus"
archetypeDir = "archetypes"
publishDir = "public"

buildDrafts = false
hasCJKLanguage = true

googleAnalytics = "UA-84081627-1"

[params]
	author = "mingrammer"
	bio = "I love computer science, automation and mathematics"
	description = "mingrammer's dev logs"
	avatar = "images/avatar.png"

	twitter = "mingrammer"
	facebook = "mingrammer"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "mingrammer-blog"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	enableTwitterCard = false
	
	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = true
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
	
[social]
	facebook-square = "https://www.facebook.com/mingrammer"
	twitter-square = "https://www.twitter.com/mingrammer"
	github-square = "https://www.github.com/mingrammer"
